_config:
  _metadata:
    name: zipkin
    version: 2.9.3
    description: |
      Zipkin is a distributed tracing system. It helps gather timing data needed to troubleshoot latency problems in microservice architectures. It manages both the collection and lookup of this data. Zipkin’s design is based on the Google Dapper paper.
  controllers:
  - type: Deployment
    controller:
      replica: 1
      ready: 0
      strategy:
        type: RollingUpdate
        unavailable: 0
        surge: 1
    pod:
      restart: Always
      dns: ClusterFirst
      termination: 30
      isPrivilege: false
      hostAliases: []
      host:
        network: false
        pid: false
        ipc: false
      annotations: []
    containers:
    - env: []
      envFrom: []
      mounts:
      - name: data
        path: "/app"
      command: []
      lifecycle: {}
      image: cargo.caicloudprivatetest.com/library/zipkin:2.9.3
      imagePullPolicy: Always
      probe: {}
      resources:
        limits:
          cpu: '2.5'
          memory: 2.5Gi
        requests:
          cpu: '0.25'
          memory: 512Mi
      securityContext:
        privileged: false
    volumes:
    - name: data
      type: Scratch
    services:
    - type: ClusterIP
      name: zipkin
      ports:
      - protocol: HTTP
        targetPort: 9441
        port: 9441
        nodePort: 0
    # - type: NodePort
    #   name: zipkin-server
    #   ports:
    #   - protocol: HTTP
    #     targetPort: 9441
    #     port: 9441
    #     nodePort: 0
