_config:
  _metadata:
    name: memcached
    version: 1.5.4
    description: |
      Free & open source, high-performance, distributed memory object caching.
  controllers:
  - containers:
    - imagePullPolicy: Always
      image: cargo.caicloudprivatetest.com/library/memcached:1.5.4-alpine
      resources:
        limits:
          cpu: '0.5'
          memory: 1Gi
        requests:
          cpu: '0.25'
          memory: 512Mi
      ports:
      - protocol: HTTP
        port: 11211
      probe: {}
    services:
    - ports:
      - protocol: HTTP
        targetPort: 11211
        port: 11211
        nodePort: 0
      name: memcached
      type: ClusterIP
    volumes: []
    pod:
      restart: Always
      dns: ClusterFirst
      termination: 30
      host:
        network: false
        pid: false
        ipc: false
    type: Deployment
    controller:
      replica: 1
      strategy:
        unavailable: 0
        surge: 1
