_config:
  _metadata:
    name: nginx
    version: 1.13.8
    description: |
      Nginx [engine x] is an HTTP and reverse proxy server, a mail proxy server, and a generic TCP/UDP proxy server.
  controllers:
  - type: Deployment
    controller:
      replica: 1
      strategy:
        type: "RollingUpdate"
    services:
    - name: nginx
      type: ClusterIP
      ports:
      - protocol: HTTP
        targetPort: 80
        port: 80
        nodePort: 0
    containers:
    - imagePullPolicy: Always
      image: cargo.caicloudprivatetest.com/library/nginx:1.13.8-alpine
      mounts: []
      env: []
      resources:
        requests:
          cpu: '0.5'
          memory: 512Mi
        limits:
          cpu: '0.5'
          memory: 512Mi
      ports:
      - protocol: HTTP
        port: 80
    volumes: []
