{{/* Generates all configmaps */}}


{{- $g := . -}}
{{- range $index, $controller := .Values._config.controllers -}}
{{- range $controller.configs }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .name }}
  labels:
    {{- include "releaseLabels" (list $g.Release.Name $g.Chart.Name) | indent 4 }}
data:
  {{- range .data }}
  {{ .key | quote }}: {{ .value | quote }}
  {{- end }}
---
{{ end -}}
{{- end -}}

