{{/* Generates all CronJobs */}}

{{- $g := . -}}




{{- $metadata := $g.Values._config._metadata -}}
{{- range $index, $controller := .Values._config.controllers -}}
{{- if eq $controller.type "CronJob" -}}
{{- $controllerName := include "onlyname" (list $g $index) | default (include "fullname" (list $g $index)) -}}



---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ $controllerName | quote }}
  labels:
    {{- include "appLabels" (list $g.Release.Name $metadata.appVersion) | indent 4 }}
    {{- include "releaselabels" (list $g.Release.Name $g.Chart.Name $metadata.project $metadata.component) | indent 4 }}
  annotations:
    {{- include "annotations" $controller.controller | indent 4 }}
{{- with $controller }}
spec:
  {{- with .controller }}
  schedule: {{ .rule | quote }}
  startingDeadlineSeconds: {{ .deadline }}
  concurrencyPolicy: {{ .policy | quote }}
  suspend: {{ .suspend }}
  {{- with .history }}
  successfulJobsHistoryLimit: {{ .success }}
  failedJobsHistoryLimit: {{ .fail }}
  {{- end }}
  {{- end }}
  jobTemplate:
    metadata:
      labels:
        {{- include "appLabels" (list $g.Release.Name $metadata.appVersion) | indent 8 }}
        {{- include "releaselabels" (list $g.Release.Name $g.Chart.Name $metadata.project $metadata.component) | indent 8 }}
      annotations:
        {{- include "annotations" $controller.controller | indent 8 }}
    spec:
      {{- with .controller }}
      parallelism: {{ .parallelism }}
      completions: {{ .completions }}
      activeDeadlineSeconds: {{ .active }}
      {{- end }}
      template:
        metadata:
          labels:
          {{- include "appLabels" (list $g.Release.Name $metadata.appVersion) | indent 12 }}
          {{- include "releaselabels" (list $g.Release.Name $g.Chart.Name $metadata.project $metadata.component) | indent 12 }}
          {{- include "controllerlabels"  $controllerName | indent 12 }}
          {{- include "schelabels" $controller.schedule | indent 12 }}
          annotations:
            {{- include "annotations" $controller.pod | indent 12 }}
        spec:
        {{- include "podspec" (list $controller $controllerName) | indent 10 }}
{{- end }}
---



{{- end -}}
{{- end -}}

