{{/* Generates all CronJobs */}}

{{- $g := . -}}





{{- range $index, $controller := .Values._config.controllers -}}
{{- if eq $controller.type "CronJob" -}}
{{- $controllerName := include "fullname" (list $g $index) -}}



---
apiVersion: batch/v2alpha1
kind: CronJob
metadata:
  name: {{ $controllerName | quote }}
  labels:
    "controller.caicloud.io/release": {{ $g.Release.Name | quote }}
    "controller.caicloud.io/chart": {{ $g.Chart.Name | quote }}
  annotations:
    {{- include "annotations" $controller.controller | indent 4 }}
{{- with $controller }}
spec:
  {{- with .controller }}
  schedule: {{ .rule | quote }}
  startingDeadlineSeconds: {{ .deadline }}
  concurrencyPolicy: {{ .policy | quote }}
  suspend: {{ .suspend }}
  {{- with .history }}
  successfulJobsHistoryLimit: {{ .success }}
  failedJobsHistoryLimit: {{ .fail }}
  {{- end }}
  {{- end }}
  jobTemplate:
    metadata:
      labels:
        "controller.caicloud.io/release": {{ $g.Release.Name | quote }}
        "controller.caicloud.io/chart": {{ $g.Chart.Name | quote }}
      annotations:
        {{- include "annotations" $controller.controller | indent 8 }}
    spec:
      {{- with .controller }}
      parallelism: {{ .parallelism }}
      completions: {{ .completions }}
      activeDeadlineSeconds: {{ .active }}
      {{- end }}
      template:
        metadata:
          labels:
            "controller.caicloud.io/release": {{ $g.Release.Name | quote }}
            "controller.caicloud.io/chart": {{ $g.Chart.Name | quote }}
            "controller.caicloud.io/name": {{ $controllerName | quote }}
            {{- include "schelabels" $controller.schedule | indent 12 }}
          annotations:
            {{- include "annotations" $controller.pod | indent 12 }}
        spec:
        {{- include "podspec" (list $controller $controllerName) | indent 10 }}
{{- end }}
---



{{- end -}}
{{- end -}}

