{{/* Generates all DaemonSets */}}

{{- $g := . -}}




{{- $metadata := $g.Values._config._metadata -}}
{{- range $index, $controller := .Values._config.controllers -}}
{{- if eq $controller.type "DaemonSet" -}}
{{- $controllerName := include "onlyname" (list $g $index) | default (include "fullname" (list $g $index)) -}}



---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ $controllerName | quote }}
  labels:
    {{- include "appLabels" (list $g.Release.Name $metadata.appVersion) | indent 4 }}
    {{- include "releaselabels" (list $g.Release.Name $g.Chart.Name) | indent 4 }}
  annotations:
    {{- include "annotations" $controller.controller | indent 4 }}
{{- with $controller }}
spec:
  {{- with .controller }}
  updateStrategy:
    {{- with .strategy }}
    type: {{ .type }}
    rollingUpdate:
      maxUnavailable: {{ .unavailable }}
    {{- end }}
  minReadySeconds: {{ .ready }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "appLabels" (list $g.Release.Name $metadata.appVersion) | indent 6 }}
      {{- include "releaselabels" (list $g.Release.Name $g.Chart.Name) | indent 6 }}
      {{- include "controllerlabels"  $controllerName | indent 6 }}
      {{- include "schelabels" $controller.schedule | indent 6 }}
  template:
    metadata:
      labels:
        {{- include "appLabels" (list $g.Release.Name $metadata.appVersion) | indent 8 }}
        {{- include "releaselabels" (list $g.Release.Name $g.Chart.Name) | indent 8 }}
        {{- include "controllerlabels"  $controllerName | indent 8 }}
        {{- include "schelabels" $controller.schedule | indent 8 }}
      annotations:
        {{- include "annotations" $controller.pod | indent 8 }}
    spec:
    {{- include "podspec" (list $controller $controllerName $g.Release.Namespace) | indent 6 }}
{{- end }}
---



{{- end -}}
{{- end -}}

