{{/* Generates all DaemonSets */}}

{{- $g := . -}}





{{- range $index, $controller := .Values._config.controllers -}}
{{- if eq $controller.type "DaemonSet" -}}
{{- $controllerName := include "fullname" (list $g $index) -}}



---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: {{ $controllerName | quote }}
  labels:
    "controller.caicloud.io/release": {{ $g.Release.Name | quote }}
    "controller.caicloud.io/chart": {{ $g.Chart.Name | quote }}
  annotations:
    {{- include "annotations" $controller.controller | indent 4 }}
{{- with $controller }}
spec:
  {{- with .controller }}
  updateStrategy:
    type: RollingUpdate
    {{- with .strategy }}
    rollingUpdate:
      maxUnavailable: {{ .unavailable }}
    {{- end }}
  minReadySeconds: {{ .ready }}
  {{- end }}
  template:
    metadata:
      labels:
        "controller.caicloud.io/release": {{ $g.Release.Name | quote }}
        "controller.caicloud.io/chart": {{ $g.Chart.Name | quote }}
        "controller.caicloud.io/name": {{ $controllerName | quote }}
        {{- include "schelabels" $controller.schedule | indent 8 }}
      annotations:
        {{- include "annotations" $controller.pod | indent 8 }}
    spec:
    {{- include "podspec" (list $controller $controllerName) | indent 6 }}
{{- end }}
---



{{- end -}}
{{- end -}}

