{{/* Generates all Deployments */}}

{{- $g := . -}}





{{- range $index, $controller := .Values._config.controllers -}}
{{- if eq $controller.type "Deployment" -}}
{{- $controllerName := include "onlyname" (list $g $index) | default (include "fullname" (list $g $index)) -}}



---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $controllerName | quote }}
  labels:
    {{- include "releaselabels" (list $g.Release.Name $g.Chart.Name) | indent 4 }}
  annotations:
    {{- include "annotations" $controller.controller | indent 4 }}
{{- with $controller }}
spec:
  {{- with .controller }}
  replicas: {{ .replica }}
  {{- with .strategy }}
  strategy:
    {{- $strategyType :=  .type | default "RollingUpdate" -}}
    {{- if eq $strategyType "Recreate" }}
    type: Recreate
    {{- else }}
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: {{ .unavailable }}
      maxSurge: {{ .surge }}
    {{- end }}
  {{- end }}
  minReadySeconds: {{ .ready }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "releaselabels" (list $g.Release.Name $g.Chart.Name) | indent 6 }}
      {{- include "controllerlabels"  $controllerName | indent 6 }}
      {{- include "schelabels" $controller.schedule | indent 6 }}
  template:
    metadata:
      labels:
        {{- include "releaselabels" (list $g.Release.Name $g.Chart.Name) | indent 8 }}
        {{- include "controllerlabels"  $controllerName | indent 8 }}
        {{- include "schelabels" $controller.schedule | indent 8 }}
      annotations:
        {{- include "annotations" $controller.pod | indent 8 }}
    spec:
    {{- include "podspec" (list $controller $controllerName) | indent 6 }}
{{- end }}
---



{{- end -}}
{{- end -}}

