{{/* Generates all Jobs */}}

{{- $g := . -}}




{{- $metadata := $g.Values._config._metadata -}}
{{- range $index, $controller := .Values._config.controllers -}}
{{- if eq $controller.type "Job" -}}
{{- $controllerName := include "onlyname" (list $g $index) | default (include "fullname" (list $g $index)) -}}



---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $controllerName | quote }}
  labels:
    {{- include "appLabels" (list $g.Release.Name $metadata.appVersion) | indent 4 }}
    {{- include "releaselabels" (list $g.Release.Name $g.Chart.Name $metadata.project $metadata.component) | indent 4 }}
  annotations:
    {{- include "annotations" $controller.controller | indent 4 }}
{{- with $controller }}
spec:
  {{- with .controller }}
  parallelism: {{ .parallelism }}
  completions: {{ .completions }}
  backoffLimit: {{ .backoffLimit }}
  activeDeadlineSeconds: {{ .active }}
  {{- end }}
  template:
    metadata:
      labels:
        {{- include "appLabels" (list $g.Release.Name $metadata.appVersion) | indent 8 }}
        {{- include "releaselabels" (list $g.Release.Name $g.Chart.Name $metadata.project $metadata.component) | indent 8 }}
        {{- include "controllerlabels"  $controllerName | indent 8 }}
        {{- include "schelabels" $controller.schedule | indent 8 }}
      annotations:
        {{- include "annotations" $controller.pod | indent 8 }}
    spec:
    {{- include "podspec" (list $controller $controllerName) | indent 6 }}
{{- end }}
---



{{- end -}}
{{- end -}}

