{{/* Generates all Jobs */}}

{{- $g := . -}}





{{- range $index, $controller := .Values._config.controllers -}}
{{- if eq $controller.type "Job" -}}
{{- $controllerName := include "fullname" (list $g $index) -}}



---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $controllerName | quote }}
  labels:
    {{- include "releaseLabels" (list $g.Release.Name $g.Chart.Name) | indent 4 }}
  annotations:
    {{- include "annotations" $controller.controller | indent 4 }}
{{- with $controller }}
spec:
  {{- with .controller }}
  parallelism: {{ .parallelism }}
  completions: {{ .completions }}
  activeDeadlineSeconds: {{ .active }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "releaseLabels" (list $g.Release.Name $g.Chart.Name) | indent 6 }}
      {{- include "controllerLabels"  $controllerName | indent 6 }}
      {{- include "schelabels" $controller.schedule | indent 6 }}
  template:
    metadata:
      labels:
        {{- include "releaseLabels" (list $g.Release.Name $g.Chart.Name) | indent 8 }}
        {{- include "controllerLabels"  $controllerName | indent 8 }}
        {{- include "schelabels" $controller.schedule | indent 8 }}
      annotations:
        {{- include "annotations" $controller.pod | indent 8 }}
    spec:
    {{- include "podspec" (list $controller $controllerName) | indent 6 }}
{{- end }}
---



{{- end -}}
{{- end -}}

