{{/* Generates all Jobs */}}

{{- $g := . -}}





{{- range $index, $controller := .Values._config.controllers -}}
{{- if eq $controller.type "Job" -}}
{{- $controllerName := include "fullname" (list $g $index) -}}



---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $controllerName | quote }}
  labels:
    "controller.caicloud.io/release": {{ $g.Release.Name | quote }}
    "controller.caicloud.io/chart": {{ $g.Chart.Name | quote }}
  annotations:
    {{- include "annotations" $controller.controller | indent 4 }}
{{- with $controller }}
spec:
  {{- with .controller }}
  parallelism: {{ .parallelism }}
  completions: {{ .completions }}
  activeDeadlineSeconds: {{ .active }}
  {{- end }}
  template:
    metadata:
      labels:
        "controller.caicloud.io/release": {{ $g.Release.Name | quote }}
        "controller.caicloud.io/chart": {{ $g.Chart.Name | quote }}
        "controller.caicloud.io/name": {{ $controllerName | quote }}
        {{- include "schelabels" $controller.schedule | indent 8 }}
      annotations:
        {{- include "annotations" $controller.pod | indent 8 }}
    spec:
    {{- include "podspec" (list $controller $controllerName) | indent 6 }}
{{- end }}
---



{{- end -}}
{{- end -}}

