{{/* Generates all secrets */}}


{{- $g := . -}}
{{- range $index, $controller := .Values._config.controllers -}}
{{- range $controller.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  labels:
    "controller.caicloud.io/release": {{ $g.Release.Name | quote }}
    "controller.caicloud.io/chart": {{ $g.Chart.Name | quote }}
type: {{ .type | default "Opaque" | quote }}
data:
  {{- range .data }}
  {{ .key | quote }}: {{ .value | quote }}
  {{- end }}
---
{{ end -}}
{{- end -}}

