{{/* Generates all dynamic volumes */}}


{{/* Creates pvc for storage class */}}
{{- $g := . -}}
{{- range $index, $controller := .Values._config.controllers -}}
{{- $controllerName := include "fullname" (list $g $index) -}}
{{- range $controller.volumes -}}
{{- if eq .type "Dynamic" }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  {{- if eq $controller.type "StatefulSet" }}
  {{ $name := $controller.controller.name | default $controllerName -}}
  name: {{ printf "%s-%s" $name .name | quote }}
  {{- else }}
  name: {{ printf "%s-%s" $controllerName .name | quote }}
  {{- end }}
  labels:
    "volume.caicloud.io/type" : {{ .type | quote }}
    "controller.caicloud.io/release": {{ $g.Release.Name | quote }}
    "controller.caicloud.io/chart": {{ $g.Chart.Name | quote }}
spec:
  accessModes:
  {{- range .source.modes }}
  - {{ . | quote }}
  {{- end }}
  storageClassName: {{ .source.class | quote }}
  resources:
    requests:
      storage: {{ .storage.request }}
    {{- if hasKey .storage "limit" }}
    limits:
      storage: {{ .storage.limit }}
    {{- end }}
---
{{ end -}}
{{- end -}}
{{- end -}}
































