_config:
  _metadata:
    name: eureka
    version: 2.0.0
    description: |
      Eureka is a REST (Representational State Transfer) based service that is primarily used in the AWS cloud for locating services for the purpose of load balancing and failover of middle-tier servers.
  controllers:
  - type: Deployment
    controller:
      replica: '1'
      ready: 0
      strategy:
        type: RollingUpdate
        unavailable: 0
        surge: 1
    pod:
      restart: Always
      dns: ClusterFirst
      termination: 30
      hostAliases: []
      host:
        network: false
        pid: false
        ipc: false
      annotations: []
    containers:
    - env: 
      - name: EUREKA_PORT
        value: 8761
      - name: EUREKA_HOST_NAME
        value: localhost
      envFrom: []
      mounts: []
      command: []
      lifecycle: {}
      image: cargo.caicloudprivatetest.com/release/eureka:2.0.0
      imagePullPolicy: Always
      probe: {}
      resources:
        limits:
          cpu: '2'
          memory: 4Gi
        requests:
          cpu: '1'
          memory: 1Gi
    volumes: []
    services:
    # - type: NodePort
    #   name: eureka-server
    #   ports:
    #   - protocol: HTTP
    #     targetPort: 8761
    #     port: 8761
    #     nodePort: 0
    - type: ClusterIP
      name: eureka-server
      ports:
      - protocol: HTTP
        targetPort: 8761
        port: 8761
        nodePort: 0
